<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */
?>
<div class="messages">
    <div class="message">
        <span>
            Need help? Visit
            <a target="_blank" href="https://github.com/Alekseon/magento2-widget-forms/wiki">
                WIKI page
            </a>
            to find more information about custom forms or contact us
            <a target="_blank" href="http://alekseon.com"><img alt="Alekseon" height="18px" src="https://alekseon.com/media/widget-forms-alekseon.png"></a>
        </span>
    </div>
</div>

