<div class="admin__page-nav">
    <div class="admin__page-nav-link">
        <h3><?= $block->getTitle() ?></h3>
        <span><?= __('Created at') ?>: <strong><?= $block->formatDate($block->getCurrentRecord()->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?></strong></span>
        <?php if ($block->getCreatedFrom()): ?>
            <br>
            <span><?= __('Created from') ?>: <strong><?= $block->getCreatedFrom() ?></strong></span>
        <?php endif ?>
    </div>
</div>
