name: ExtDN Actions
on: [push]
jobs:
  unit-tests:
    name: Magento 2 Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker://yireo/github-actions-magento-unit-tests:7.3
        env:
          MAGENTO_VERSION: '2.3.4'
          MODULE_NAME: Alekseon_CustomFormsBuilder
          COMPOSER_NAME: alekseon/custom-forms-builder
          REPOSITORY_URL: https://repo.magento.com/
          MAGENTO_MARKETPLACE_USERNAME: ${{ secrets.MAGENTO_MARKETPLACE_USERNAME }}
          MAGENTO_MARKETPLACE_PASSWORD: ${{ secrets.MAGENTO_MARKETPLACE_PASSWORD }}
